name: annotation
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - python = 3.10
    # function
    - prokka = 1.14.6 
    # taxonomy
    - diamond = 2.1.7
    - dram = 1.4.6
#    - gtdbtk = 2.3.2
#    - prodigal = 2.6.3
#    - centrifuge = 1.0.4 # requires python <3
    - kraken2 = 2.1.3
#    - bowtie2 = 2.5.1
#    - bwa = 0.7.17
#    - samtools = 1.17
#    - metaphlan = 4.0.6

# conda env create -f /fs/project/PAS1117/ricardo/metaG/annotation_config.yml