name: binning
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - python = 3.10
    - metabat2 = 2.15
    #- das_tool = 1.1.6
    - checkm-genome = 1.2.2
    - numpy # for checkm
    - matplotlib # for checkm
    - pysam # for checkm
    - hmmer # for checkm
    - prodigal # for checkm
    - pplacer # for checkm
    - maxbin2 = 2.2.7
    #- fraggenescan = 1.31 # for maxbin2
    #- hmmer = 3.3.2 # for maxbin2
    #- idba = 1.1.3 # for maxbin2