name: mag_purify
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - magpurify = 2.1.2

    # to download the reference database
    #  wget https://zenodo.org/record/3688811/files/MAGpurify-db-v1.0.tar.bz2
    # tar -jxvf MAGpurify-db-v1.0.tar.bz2
    # mv MAGpurify-db-v1.0/ /fs/project/PAS1117/ricardo/mag_purify/